// Addon loader (design §D.3/§E) — resolve + load the prebuilt N-API `.node` from
// `crates/zero-migrate-node` (Phase C) and type its exposed surface.
//
// The addon is the V8-free Rust core (`host-pg` + bundled rusqlite, no compio, no
// io_uring, cross-platform). It exposes:
//  - sync, DB-free: `irVersion()`, `loadVerify(...)` (§C.5)
//  - async, host-driven (fire-and-resolve over a `hostDriver` TSFN): `applyIr(...)`,
//    `apply(...)`, `status(...)`, `history(...)` (§C.5/§D.1)
//
// The host-driver callback contract is `hostDriver([request, done]) => void` —
// napi delivers `(request, done)` as a SINGLE array arg (§B.3). See `driver-pg.ts`.

import { createRequire } from "node:module";

// The addon's wire DTOs + verb signatures are GENERATED by napi-rs from the Rust
// `#[napi]` source (`crates/zero-migrate-node/src/wire.rs` + `bridge.rs`) into
// `crates/zero-migrate-node/index.d.ts` — the SINGLE source of truth (redesign step
// 5a). We import them here (a type-only import — no runtime dependency on the crate;
// the `.node` is still loaded via `createRequire`) and re-export the driver cell DTOs
// so `driver-pg.ts`/`driver-mysql2.ts` consume them instead of hand-copying.
import type {
  JsCell as GenJsCell,
  JsRow as GenJsRow,
  JsRequest as GenJsRequest,
  JsReply as GenJsReply,
  JsError as GenJsError,
  ApplyRequest,
  StatusRequest,
  HistoryRequest,
  ApplyReply,
  StatusReply,
  HistoryReply,
  LoadVerifyReply,
} from "../../../crates/zero-migrate-node/index.js";

export type {
  ApplyRequest,
  StatusRequest,
  HistoryRequest,
  ApplyReply,
  StatusReply,
  HistoryReply,
  LoadVerifyReply,
};

/** The neutral driver cell DTOs — the single source of truth from the generated
 *  addon `index.d.ts`. Re-exported so the host drivers import (not re-declare) them. */
export type JsCell = GenJsCell;
export type JsRow = GenJsRow;
export type JsRequest = GenJsRequest;
export type JsReply = GenJsReply;
export type JsError = GenJsError;

/** The `hostDriver([request, done]) => void` callback the async entrypoints drive
 *  (§B.3). Shaped exactly by the generated `JsRequest`/`JsReply`/`JsError` DTOs. */
export type AddonHostDriver = (
  args: [request: JsRequest, done: (err: JsError | null, reply: JsReply | null) => void],
) => void;

/** The addon's exposed surface — the TYPED verb boundary (redesign step 5a): every
 *  verb takes + returns a generated `#[napi(object)]` DTO, NO JSON strings. */
export interface MigrateAddon {
  /** The IR-format version this addon was built against — the single source of
   *  truth across the boundary (§D.1). */
  irVersion(): number;

  /** Sync, DB-free load + verify of an `.ir.json` document (§C.5). Returns a typed
   *  `LoadVerifyReply` (`registry` crosses typed, not a JSON string). */
  loadVerify(
    irJson: string,
    deployingApp: string,
    dialect: string,
    registry: Record<string, string>,
  ): LoadVerifyReply;

  /** HOST-AUTHORING apply (§D.1): take a typed `ApplyRequest` (the `.ir.json`
   *  envelope as a JS value), LOWER it in Rust (stamp `owner_app` + fold
   *  `Checksum::of_ir`), then drive `executor::apply` over the host driver. Resolves
   *  to a typed `ApplyReply`. */
  applyIr(hostDriver: AddonHostDriver, req: ApplyRequest): Promise<ApplyReply>;

  /** `status` over the host driver (§C.5). Resolves to a typed `StatusReply`. */
  status(hostDriver: AddonHostDriver, req: StatusRequest): Promise<StatusReply>;

  /** `history` over the host driver (§C.5). Resolves to a typed `HistoryReply`. */
  history(hostDriver: AddonHostDriver, req: HistoryRequest): Promise<HistoryReply>;
}

let cached: MigrateAddon | null = null;

/**
 * Load the prebuilt `.node`. Resolution order (§E — napi-rs prebuild convention):
 *  1. `ZERO_MIGRATE_ADDON_PATH` env override (an explicit `.node` path — used in dev
 *     / by the oracle to point at the freshly-`napi build`'d artifact).
 *  2. the bundled `native/migrate.<platform>.node` shipped with this package.
 *
 * There is deliberately NO hard-coded sibling-crate fallback: this is a standalone
 * npm package with no monorepo-relative build layout to assume. In dev, point
 * `ZERO_MIGRATE_ADDON_PATH` at the `napi build` output.
 *
 * @throws if no `.node` can be resolved/loaded (with the tried paths).
 */
export function loadAddon(): MigrateAddon {
  if (cached) return cached;
  const require = createRequire(import.meta.url);
  const tried: string[] = [];

  const candidates = addonCandidates();
  for (const p of candidates) {
    try {
      // eslint-disable-next-line @typescript-eslint/no-var-requires
      const mod = require(p) as MigrateAddon;
      if (mod && typeof mod.irVersion === "function") {
        cached = mod;
        return mod;
      }
      tried.push(`${p} (loaded but missing irVersion)`);
    } catch (e) {
      tried.push(`${p} (${(e as Error).message})`);
    }
  }
  throw new Error(
    "zero-migrate-engine: could not load the native addon (.node). Tried:\n  " +
      tried.join("\n  ") +
      "\nSet ZERO_MIGRATE_ADDON_PATH to an explicit .node path, or run `napi build` in " +
      "crates/zero-migrate-node and ship native/.",
  );
}

/** The ordered `.node` candidate paths (see {@link loadAddon}). */
function addonCandidates(): string[] {
  const out: string[] = [];
  const override = process.env.ZERO_MIGRATE_ADDON_PATH;
  if (override) out.push(override);
  const { platform, arch } = process;
  // The napi-rs default triple spelling (linux-x64-gnu, darwin-arm64, win32-x64, …).
  const abi = platform === "linux" ? "-gnu" : "";
  const triple = `${platform}-${arch}${abi}`;
  // Bundled with the package (populated by the prebuild step). `import.meta.url` is
  // the compiled `dist/index.js`, so the package root is `../` and `native/` sits
  // beside `dist/`.
  out.push(new URL(`../native/migrate.${triple}.node`, import.meta.url).pathname);
  out.push(new URL(`../native/index.node`, import.meta.url).pathname);
  return out;
}

/** The addon's IR-format version — the single source of truth (§D.1). */
export function currentIrVersion(): number {
  return loadAddon().irVersion();
}
